### ISSUE TITLE
debug模式编译问题请教

### ISSUE THREAD

**Issue by microhuang** [DoOR-Team/scipoptsuite#1]
朋友你好，

我想使用debug模式编译源码，发现SCIPdebugMsg等语句输出不生效：

cmake -DCMAKE_BUILD_TYPE=Debug -DDEBUGSOL=on -DNOBLKBUFMEM=on -DGCG=off ..

使用：

cmake -DCMAKE_BUILD_TYPE=Debug -DDEBUGSOL=on -DNOBLKBUFMEM=on -DGCG=off -DSCIP_DEBUG=on ..

则报告没有SCIP_DEBUG选项，请问如果才能开启源码中的debug输出，谢谢！

**Comment by jpbirdy** [comment]
您好，您所指的debug输出指的是什么？我这里编译后可以执行并输出如下日志：
![image](https://user-images.githubusercontent.com/3351531/105627316-3943eb80-5e71-11eb-9aaa-208929faf925.png)

**Comment by jpbirdy** [comment]
@microhuang 如无疑问我关闭这个问题了。我们团队主要做源码阅读的工作，可以到ZIB团队官网上获得更多信息，也可以与我们团队交流。

**Comment by microhuang** [comment]
使用：cmake -DCMAKE_BUILD_TYPE=Debug -DDEBUGSOL=on -DNOBLKBUFMEM=on -DGCG=off ..  编译后，
源码中：SCIPdebugMsg(scip, "After additional fixings: %d / %d\n",*nfixings, ntargetfixings);      均无实际输出。

**Comment by microhuang** [comment]
使用：cmake -DCMAKE_BUILD_TYPE=Debug -DDEBUGSOL=on -DNOBLKBUFMEM=on -DGCG=off .. 编译后，
源码中：SCIPdebugMsg(scip, "After additional fixings: %d / %d\n",*nfixings, ntargetfixings);  这类语句均无实际输出。
